name: 'llama_app'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
repository: 'https://github.com/General-Developer/whisper_library'
homepage: 'https://www.youtube.com/@general_dev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
  general_lib: '^0.0.71'
  general_lib_flutter: '^0.0.42'
  packagex: '^1.0.3'
  general_framework: '^0.0.31'
  path: '^1.9.0'
  general_system_device: '^0.0.56'
  llama_library: ^0.0.3
  llama_library_flutter: '^0.0.3'
  ggml_library_flutter: '^0.0.10'
  file_picker: '^9.0.2'
  database_universe: '^1.1.4'
  media_universe: '^0.0.3'
  media_universe_flutter: '^0.0.3'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  msix: '^3.16.8'
  build_runner: 'any'
flutter:
  uses-material-design: true
project:
  type: ''
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
packagex:
  name: 'llama_app'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_build_arguments:
    - '--split-per-abi'
    - '--build-name'
    - '0.0.0'
    - '--build-number'
    - '0'
    - '--obfuscate'
    - '--split-debug-info'
    - 'packagex-build-debug'
  dart_compile_exe_arguments:
    - '--save-debugging-info=packagex-compile-debug'
  uploads:
    - platform_type: 'github'
      github_username: 'General-Developer'
      github_tag: 'release'
      github_is_org: true
      github_repository_name: 'llama_library'
  packages:
    - dart_target: 'llama_app'
      flutter_target: 'main'
      dart_name: 'llama_app'
      flutter_name: 'llama_app'
      output_name: 'llama-app'
msix_config:
  display_name: 'llama_app'
  install_certificate: false
