// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbvlGnZUslg22lxlgWOh0BihVhWoTXR4Y',
    appId: '1:661230908102:web:c57a68566c910f32de1dc7',
    messagingSenderId: '661230908102',
    projectId: 'giraffe-diaries-287f9',
    authDomain: 'giraffe-diaries-287f9.firebaseapp.com',
    storageBucket: 'giraffe-diaries-287f9.firebasestorage.app',
    measurementId: 'G-9KRW5BYGYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKWfhP_aD3zlWB2l_ziIUWA_-Y_O5DWzI',
    appId: '1:661230908102:android:33d1ff9243095236de1dc7',
    messagingSenderId: '661230908102',
    projectId: 'giraffe-diaries-287f9',
    storageBucket: 'giraffe-diaries-287f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBraYga6o6U0tqqCID1j57HAKs0iq1kdgM',
    appId: '1:661230908102:ios:f293285966698329de1dc7',
    messagingSenderId: '661230908102',
    projectId: 'giraffe-diaries-287f9',
    storageBucket: 'giraffe-diaries-287f9.firebasestorage.app',
    iosBundleId: 'com.example.giraffeDiaries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBraYga6o6U0tqqCID1j57HAKs0iq1kdgM',
    appId: '1:661230908102:ios:f293285966698329de1dc7',
    messagingSenderId: '661230908102',
    projectId: 'giraffe-diaries-287f9',
    storageBucket: 'giraffe-diaries-287f9.firebasestorage.app',
    iosBundleId: 'com.example.giraffeDiaries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbvlGnZUslg22lxlgWOh0BihVhWoTXR4Y',
    appId: '1:661230908102:web:260bc5a3163dee0ede1dc7',
    messagingSenderId: '661230908102',
    projectId: 'giraffe-diaries-287f9',
    authDomain: 'giraffe-diaries-287f9.firebaseapp.com',
    storageBucket: 'giraffe-diaries-287f9.firebasestorage.app',
    measurementId: 'G-RD4PNDT1CG',
  );
}
